

#' Title
#'
#' @param data data frame
#' @param .p A predicate function to be applied to the columns or a logical
#'   vector. The variables for which .predicate is or returns TRUE are selected.
#'   This argument is passed to rlang::as_function() and thus supports
#'   quosure-style lambda functions and strings representing function names.
#' @param ... arguments passed to \code{\link{scale}}
#'
#' @return data frame
#' @export
#'
df_scale_if <- function(data, .p, ...) {
  stopifnot(is.data.frame(data))

  data %>%
    dplyr::mutate_if(.p, ~as.vector(scale(., ...))) %>%
    dplyr::as_data_frame()
}


#' Title
#'
#' @param data data frame
#' @param .vars A list of columns generated by \code{\link[dplyr]{vars}}, or a character vector of
#'   column names, or a numeric vector of column positions..
#' @param ... arguments passed to \code{\link{scale}}
#'
#' @return data frame
#' @export
#'
df_scale_at <- function(data, .p, ...) {
  stopifnot(is.data.frame(data))

  data %>%
    dplyr::mutate_if(.p, ~as.vector(scale(., ...))) %>%
    dplyr::as_data_frame()
}


#' Title
#'
#' @param data data frame
#' @param .vars A list of columns generated by \code{\link[dplyr]{vars}}, or a character vector of
#'   column names, or a numeric vector of column positions.
#' @inheritParams biodatacoreUtils::as_filler
#'
#' @return data frame
#' @export
#'
df_fill_zero_at <- function(data, .vars, .fill) {
  stopifnot(is.data.frame(data))

  data %>%
    dplyr::mutate_at(.vars, ~biodatacoreUtils::fill_if(., ~.x == 0, .fill))
}

#' Title
#'
#' @param data data frame
#' @param .vars A list of columns generated by \code{\link[dplyr]{vars}}, or a character vector of
#'   column names, or a numeric vector of column positions.
#' @inheritParams biodatacoreUtils::as_filler
#'
#' @return data frame
#' @export
#'
df_fill_na_at <- function(data, .vars, .fill) {
  stopifnot(is.data.frame(data))

  data %>%
    dplyr::mutate_at(.vars, ~biodatacoreUtils::fill_if(., ~rlang::is_na(.x), .fill))
}


#' Title
#'
#' @param data data frame
#'
#' @return data frame
#' @export
#'
df_remove_rows_with_na <- function(data) {
  stopifnot(is.data.frame(data))
  data[stats::complete.cases(data), ]
}
