

#' Title
#'
#' @param data data frame
#' @param ... arguments passed to \code{\link{scale}}
#'
#' @return data frame
#' @export
#'
df_scale_numeric_vars <- function(data, ...) {
  stopifnot(is.data.frame(data))

  data %>%
    dplyr::mutate_if(is.numeric, ~as.vector(scale(., ...))) %>%
    dplyr::as_data_frame()
}

#' Title
#'
#' @param data data frame
#'
#' @return data frame
#' @export
#'
df_remove_rows_with_na <- function(data) {
  stopifnot(is.data.frame(data))
  data[stats::complete.cases(data), ]
}

#' Title
#'
#' @param data data
#' @param .vars A list of columns generated by \code{\link[dplyr]{vars}}, or a character vector of
#'   column names, or a numeric vector of column positions.
#' @param ... arguments passed to \code{\link{log}}
#'
#' @return data frame
#' @export
#'
df_log_at <- function(data, .vars, ...) {
  stopifnot(is.data.frame(data))
  .vars <- rlang::enquo(.vars)
  data %>%
    dplyr::mutate_at(rlang::UQ(.vars), ~log(.x, ...))
}

#' Title
#'
#' @param data data frame
#' @param .vars A list of columns generated by \code{\link[dplyr]{vars}}, or a character vector of
#'   column names, or a numeric vector of column positions.
#' @inheritParams biodatacoreUtils::as_filler
#'
#' @return data frame
#' @export
#'
df_fill_zero_at <- function(data, .vars, .f) {
  stopifnot(is.data.frame(data))
  .vars <- rlang::enquo(.vars)
  data %>%
    dplyr::mutate_at(rlang::UQ(.vars), ~biodatacoreUtils::fill_if(., ~.x == 0, .f))
}

#' Title
#'
#' @param data data frame
#' @param .vars A list of columns generated by \code{\link[dplyr]{vars}}, or a character vector of
#'   column names, or a numeric vector of column positions.
#' @inheritParams biodatacoreUtils::as_filler
#'
#' @return data frame
#' @export
#'
df_fill_na_at <- function(data, .vars, .f) {
  stopifnot(is.data.frame(data))
  .vars <- rlang::enquo(.vars)

  data %>%
    dplyr::mutate_at(rlang::UQ(.vars), ~biodatacoreUtils::fill_if(., ~rlang::is_na(.x), .f))
}
